### ISSUE TITLE
Feature: Telegram and Discord Integration

### ISSUE THREAD

**Issue by pomadev** [pomadev/dollar-cost-averaging-bot#13]
## Description
Expand notification capabilities beyond LINE to include Telegram and Discord, allowing users to choose their preferred communication platform for receiving DCA bot notifications.

## Implementation Details
- Abstract notification system to support multiple providers
- Implement Telegram Bot API integration
- Implement Discord Webhook integration
- Allow users to configure multiple notification channels

## Key Features
1. **Telegram Integration**
   - Create Telegram bot
   - Support for rich message formatting
   - Interactive buttons for quick actions
   - Group chat support

2. **Discord Integration**
   - Webhook-based notifications
   - Embed messages with rich formatting
   - Role-based mentions for alerts
   - Thread support for purchase history

3. **Multi-Channel Support**
   - Configure different channels for different events
   - Priority-based notification routing
   - Fallback channels for critical alerts
   - Channel-specific formatting

## Notification Types
- Purchase confirmations
- Error alerts
- Performance summaries
- Configuration changes
- System maintenance notices

## Acceptance Criteria
- [ ] Telegram bot can send formatted messages
- [ ] Discord webhooks work reliably
- [ ] Users can configure preferred channels
- [ ] Message formatting is platform-appropriate
- [ ] Delivery confirmation is tracked
- [ ] Failed notifications are retried
- [ ] Configuration supports multiple channels
- [ ] Documentation includes setup guides

## Configuration Example
```yaml
notifications:
  providers:
    - type: line
      enabled: true
      user_id: 
      events: [purchase, error, summary]
    
    - type: telegram
      enabled: true
      chat_id: 
      bot_token: 
      events: [purchase, error]
    
    - type: discord
      enabled: true
      webhook_url: 
      events: [summary]
      
  formatting:
    use_emojis: true
    include_prices: true
    timezone: Asia/Tokyo
```

## Implementation Architecture
```go
type NotificationProvider interface {
    SendPurchaseNotification(purchase Purchase) error
    SendErrorNotification(err error) error
    SendSummaryNotification(summary Summary) error
    IsAvailable() bool
}
```

**Priority**: Medium
**Estimated Effort**: Medium
