### ISSUE TITLE
Feature: Dynamic Purchase Amount Adjustment

### ISSUE THREAD

**Issue by pomadev** [pomadev/dollar-cost-averaging-bot#14]
## Description
Implement intelligent purchase amount adjustments based on market conditions, allowing the bot to buy more during dips and potentially less during peaks, maximizing the effectiveness of the DCA strategy.

## Implementation Details
- Integrate technical indicators (RSI, moving averages)
- Create rule-based adjustment system
- Implement backtesting capabilities
- Add safety limits to prevent over-investment

## Key Features
1. **Market Condition Detection**
   - RSI (Relative Strength Index) calculation
   - Moving average comparisons
   - Volatility index tracking
   - Fear & Greed index integration

2. **Purchase Multipliers**
   - Configurable multipliers for different conditions
   - Example: 2x purchases when RSI < 30 (oversold)
   - Example: 0.5x purchases when RSI > 70 (overbought)
   - Maximum and minimum investment limits

3. **Rule Engine**
   - Combine multiple indicators
   - Priority-based rule execution
   - Dry-run mode for testing
   - Historical performance analysis

4. **Safety Features**
   - Monthly investment caps
   - Maximum multiplier limits
   - Emergency stop conditions
   - Notification of adjustments

## Acceptance Criteria
- [ ] Technical indicators are calculated correctly
- [ ] Purchase amounts adjust based on rules
- [ ] Safety limits are enforced
- [ ] All adjustments are logged
- [ ] Notifications explain why amounts were adjusted
- [ ] Backtesting shows strategy effectiveness
- [ ] Configuration is intuitive
- [ ] Performance impact is minimal

## Configuration Example
```yaml
dynamic_dca:
  enabled: true
  base_amount_jpy: 10000
  
  indicators:
    - type: rsi
      period: 14
      oversold: 30
      overbought: 70
      
    - type: ma_crossover
      fast_period: 20
      slow_period: 50
      
  rules:
    - name: "Buy the dip"
      condition: "rsi < 30"
      multiplier: 2.0
      max_amount: 30000
      
    - name: "Reduce on peak"
      condition: "rsi > 70"
      multiplier: 0.5
      
    - name: "Trend following"
      condition: "price < ma_20"
      multiplier: 1.5
      
  safety:
    max_monthly_investment: 200000
    max_multiplier: 3.0
    min_multiplier: 0.3
```

## Technical Considerations
- Cache indicator calculations
- Use reliable data sources for indicators
- Handle edge cases (e.g., not enough historical data)
- Consider API costs for additional data
- Plan for indicator calculation errors

**Priority**: Low
**Estimated Effort**: High
