### ISSUE TITLE
Feature: Multi-Currency Support

### ISSUE THREAD

**Issue by pomadev** [pomadev/dollar-cost-averaging-bot#17]
## Description
Extend the bot to support multiple fiat currencies beyond JPY, allowing users from different countries to use their local currency for DCA investments.

## Implementation Details
- Add currency conversion capabilities
- Support for multiple fiat currencies (USD, EUR, GBP, etc.)
- Configure preferred base currency per user
- Handle exchange rate fluctuations

## Key Features
1. **Currency Configuration**
   - User-defined base currency
   - Multi-currency account support
   - Currency preference per exchange
   - Automatic currency detection

2. **Exchange Rate Management**
   - Real-time exchange rate fetching
   - Caching for performance
   - Historical rate tracking
   - Rate source configuration

3. **Purchase Calculations**
   - Convert amounts to exchange's base currency
   - Track purchases in user's currency
   - Fee calculations in correct currency
   - Accurate reporting across currencies

4. **Reporting & Analytics**
   - Performance in user's base currency
   - Currency conversion impact analysis
   - Multi-currency portfolio view
   - Tax reporting in local currency

## Supported Currencies (Initial)
- USD (US Dollar)
- EUR (Euro)
- GBP (British Pound)
- JPY (Japanese Yen)
- AUD (Australian Dollar)
- CAD (Canadian Dollar)
- CHF (Swiss Franc)

## Acceptance Criteria
- [ ] Users can select their base currency
- [ ] Purchases work with any supported currency
- [ ] Exchange rates are accurate and current
- [ ] Reports show values in user's currency
- [ ] Currency conversion fees are tracked
- [ ] Configuration supports multiple currencies
- [ ] API responses include currency information
- [ ] Documentation covers all supported currencies

## Configuration Example
```yaml
currency:
  base_currency: USD
  
  supported_currencies:
    - USD
    - EUR
    - GBP
    - JPY
    
  exchange_rate_provider: "exchangerate-api"
  cache_duration: 3600  # seconds
  
  purchase_amounts:
    BTC: 
      amount: 100
      currency: USD
    ETH:
      amount: 75
      currency: EUR
      
  reporting:
    display_currency: USD
    include_conversion_fees: true
```

## Technical Considerations
- Handle decimal precision for different currencies
- Consider exchange's supported currency pairs
- Cache exchange rates appropriately
- Handle rate limiting from FX providers
- Plan for currency provider failures

**Priority**: Medium
**Estimated Effort**: Medium
