### ISSUE TITLE
Feature: Advanced Scheduling Options

### ISSUE THREAD

**Issue by pomadev** [pomadev/dollar-cost-averaging-bot#8]
## Description
Enhance the bot's scheduling capabilities beyond simple Pub/Sub triggers. Allow users to configure multiple DCA schedules with different parameters for more sophisticated investment strategies.

## Implementation Details
- Support multiple schedule configurations
- Add day-of-week and time-of-day preferences
- Implement holiday calendar integration
- Create schedule validation logic
- Add schedule conflict detection

## Key Features
1. **Multiple Schedules**
   - Different schedules for different cryptocurrencies
   - Varying amounts based on schedule
   - Example: Large BTC purchase monthly, small ETH purchase weekly

2. **Time Preferences**
   - Execute at specific times to catch market patterns
   - Randomize execution time within a window
   - Avoid weekends or specific days

3. **Holiday Handling**
   - Skip purchases on market holidays
   - Double up before/after holidays (optional)
   - Support for different market calendars (US, JP, etc.)

## Acceptance Criteria
- [ ] Can configure multiple independent schedules
- [ ] Each schedule has its own cryptocurrency and amount settings
- [ ] Time-of-day preferences are respected
- [ ] Holiday calendar integration works
- [ ] Schedules can be enabled/disabled independently
- [ ] Clear logging of why a schedule was skipped
- [ ] LINE notifications indicate which schedule triggered

## Configuration Example
```yaml
schedules:
  - name: "Weekly BTC DCA"
    enabled: true
    frequency: weekly
    day_of_week: monday
    time_window: "09:00-11:00"
    cryptocurrency: BTC
    amount_jpy: 10000
    
  - name: "Monthly ETH Investment"
    enabled: true
    frequency: monthly
    day_of_month: 15
    cryptocurrency: ETH
    amount_jpy: 50000
    skip_weekends: true
```

**Priority**: Medium
**Estimated Effort**: Medium
